### ISSUE TITLE
Ngx-Favicon is not working on Angular 9

### ISSUE THREAD

**Issue by stuurman** [imaka/Ngx-Favicon#2]
Thanks for the useful library!
Works fine on Angular 7.
When I update to 9 it however stops working with the following error:
main.ts:20 TypeError: Object(...)(...).querySelector is not a function
    at AngularFaviconService.getFavicon (angular-favicon.js:33)
    at AngularFaviconService.setFavicon (angular-favicon.js:43)

**Comment by imaka** [comment]
Sorry for my late reply!

It looks like the newer Angular versions changed the location of one library I was using. Thanks for letting me know, I will publish a new version as soon as possible.
